### ISSUE TITLE
Scroll bar appearance

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/brand-diceytech#3]
Change made in Dicey-Tech/frontend-app-teacher-dashboard#5 should be uniform across all MFEs.

**Comment by Salik-Rafiq** [comment]
OK. so I tried to test this using the module alias facility but this did not work.

So I tested it by copying the changes to the appropriate file in the @edx/brand folder in my node-modules and it worked. So I'm just gonna push it and rebuild.

Might want to ask the tutor/devstack how this works/doesn't work. It could be something with tutor rather than devstack??

**Comment by BbrSofiane** [comment]
Just to confirm is this ready to test?

**Comment by Salik-Rafiq** [comment]
Yes. git it a go. It did work for me in classroom. I think you need to rebuild node_modules.

Which reminds - need to update the version number?
